### ISSUE TITLE
Broken table layout when using child rows

### ISSUE THREAD

**Issue by Wirone** [ashl1/datatables-rowsgroup#7]
At the beginning: thanks for plugin! I needed it and works well in general.

But I have problem with [child rows](https://datatables.net/examples/api/row_details.html). When child row is expanded for row with grouped cell, table's layout brokes.

I've created [live demo](http://live.datatables.net/sekarefo/1).

It can be handled with more complex code for child rows' displaying/hiding, but maybe there's a possibility to support it in some way on this plugin's level.

**Comment by ShiftyMcCool** [comment]
I'm having this exact same issue.  @Wirone you mentioned that it can be handled with more complex code.  Have you worked out exactly how to do it or is it just speculation?  If you have, mind sharing what you did?  I can't seem to get it working correctly no matter how deep I dig.

Thanks!

**Comment by Wirone** [comment]
@ShiftyMcCool I have working code, [this is live demo](http://live.datatables.net/sekarefo/2) (I've updated previous demo and added custom behaviour in comparison to regular one).

What is done there:
- Rows grouped must have common `data` attached to `tr`
- After clicking details button last grouped (or last displayed) row is searched
- Details are displayed in last row's child container
- Only details from one row from each group can be displayed (opening details for other row from group overwrites previously opened details)

Hope this helps :-)

**Comment by ashl1** [comment]
Hello.
Thanks for advice.
There are several behaviors for the problem you mentioned. At least two.

1. the child row will be shown at next line of line you clicked on
2. the child row will be shown after all  lines in group. This is more complicated because group might be separated in subgroups. They might be separated in another subgroups and so on. And if  the table is big and and group is big you should think about auto scrolling to the child row.

What do you think about the UX of these behaviors? Why is the second method preferable to the first?

**Comment by Wirone** [comment]
Sorry @ashl1 for not answering your question and wasting your time 😅 I'll close it now as it's most probably outdated and I don't need it anymore.
